import type { Player, Practice, Match, Report, StaffMember, Drill } from '@/lib/types'

// ─── Players ──────────────────────────────────────────────────────────────────
export const MOCK_PLAYERS: Player[] = [
  { id: 1,  number: 1,  name: 'Diogo Alves',    position: 'Goalkeeper',   nationality: '🇵🇹 Portugal', age: 28, status: 'Fit' },
  { id: 2,  number: 2,  name: 'Tiago Santos',   position: 'Right Back',   nationality: '🇵🇹 Portugal', age: 24, status: 'Fit' },
  { id: 3,  number: 5,  name: 'André Brito',    position: 'Centre Back',  nationality: '🇧🇷 Brazil',   age: 27, status: 'Fit' },
  { id: 4,  number: 6,  name: 'Luís Dias',      position: 'Centre Back',  nationality: '🇵🇹 Portugal', age: 26, status: 'Injured' },
  { id: 5,  number: 3,  name: 'Fábio Sousa',    position: 'Left Back',    nationality: '🇵🇹 Portugal', age: 23, status: 'Fit' },
  { id: 6,  number: 8,  name: 'Rafael Costa',   position: 'Defensive Mid',nationality: '🇧🇷 Brazil',   age: 29, status: 'Fit' },
  { id: 7,  number: 10, name: 'Bruno Lopes',    position: 'Attacking Mid',nationality: '🇵🇹 Portugal', age: 25, status: 'Fit' },
  { id: 8,  number: 7,  name: 'Marco Oliveira', position: 'Right Winger', nationality: '🇵🇹 Portugal', age: 22, status: 'Doubtful' },
  { id: 9,  number: 11, name: 'João Ferreira',  position: 'Left Winger',  nationality: '🇵🇹 Portugal', age: 24, status: 'Suspended' },
  { id: 10, number: 9,  name: 'Paulo Neves',    position: 'Striker',      nationality: '🇳🇬 Nigeria',  age: 27, status: 'Fit' },
  { id: 11, number: 19, name: 'Carlos Ramos',   position: 'Striker',      nationality: '🇵🇹 Portugal', age: 21, status: 'Fit' },
]

// ─── Practices ────────────────────────────────────────────────────────────────
export const MOCK_PRACTICES: Practice[] = [
  { id: 1, date: '2026-03-06', time: '09:00', type: 'Tactical',   duration: '90 min', location: 'Main Pitch',       attendance: 22, notes: 'Pre-match shape work — 4-3-3 press triggers' },
  { id: 2, date: '2026-03-05', time: '10:00', type: 'Technical',  duration: '75 min', location: 'Training Ground B',attendance: 20, notes: 'Finishing drills and crossing patterns' },
  { id: 3, date: '2026-03-04', time: '09:30', type: 'Physical',   duration: '60 min', location: 'Gym',              attendance: 18, notes: 'High-intensity interval training' },
  { id: 4, date: '2026-03-03', time: '09:00', type: 'Recovery',   duration: '45 min', location: 'Indoor Facility',  attendance: 22, notes: 'Post-match recovery session — pool and mobility work' },
  { id: 5, date: '2026-02-28', time: '10:30', type: 'Set Pieces', duration: '60 min', location: 'Main Pitch',       attendance: 21, notes: 'Corner kick routines and defensive organization' },
]

// ─── Matches ──────────────────────────────────────────────────────────────────
export const MOCK_MATCHES: Match[] = [
  { id: 1, date: '2026-03-08', time: '15:00', competition: 'Primeira Liga',        opponent: 'FC Porto',   venue: 'Away', location: 'Estádio do Dragão',             goalsFor: null, goalsAgainst: null, result: 'Upcoming', notes: 'Derby match — high intensity expected' },
  { id: 2, date: '2026-03-01', time: '18:00', competition: 'Primeira Liga',        opponent: 'Sporting CP',venue: 'Home', location: 'Estádio Municipal',              goalsFor: 2, goalsAgainst: 1, result: 'Win',      notes: "Great second-half performance. Goals by Neves (52') and Ramos (78')" },
  { id: 3, date: '2026-02-22', time: '20:00', competition: 'Taça de Portugal',     opponent: 'SC Braga',   venue: 'Away', location: 'Estádio Municipal de Braga',     goalsFor: 1, goalsAgainst: 1, result: 'Draw',     notes: 'Overtime played. Progressed on penalties (4-3)' },
  { id: 4, date: '2026-02-15', time: '16:00', competition: 'Primeira Liga',        opponent: 'Benfica',    venue: 'Home', location: 'Estádio Municipal',              goalsFor: 0, goalsAgainst: 2, result: 'Loss',     notes: 'Poor defensive shape in first half. Review set piece conceding.' },
  { id: 5, date: '2026-02-08', time: '18:00', competition: 'Primeira Liga',        opponent: 'Vitória SC', venue: 'Away', location: 'Estádio D. Afonso Henriques',    goalsFor: 3, goalsAgainst: 0, result: 'Win',      notes: 'Dominant display. Clean sheet. Pressing worked well.' },
]

// ─── Reports ──────────────────────────────────────────────────────────────────
export const MOCK_REPORTS: Report[] = [
  { id: 1, name: 'Match Report — FC Porto 2:1',           date: 'Mar 2, 2026',  status: 'Ready',      type: 'Match' },
  { id: 2, name: 'Weekly Training Load Summary',           date: 'Mar 1, 2026',  status: 'Ready',      type: 'Training' },
  { id: 3, name: 'Injury Assessment — A. Costa',           date: 'Feb 27, 2026', status: 'Processing', type: 'Medical' },
  { id: 4, name: 'Scouting — R. Oliveira (Braga)',         date: 'Feb 24, 2026', status: 'Ready',      type: 'Scouting' },
  { id: 5, name: 'March Fixture & Travel Plan',            date: 'Feb 20, 2026', status: 'Ready',      type: 'Planning' },
  { id: 6, name: 'Mid-Season Performance Review',          date: 'Jan 31, 2026', status: 'Processing', type: 'Performance' },
]

// ─── Staff ────────────────────────────────────────────────────────────────────
export const MOCK_STAFF: StaffMember[] = [
  { id: 1, name: 'James Hartley',  email: 'j.hartley@club.com', role: 'Head Coach',    status: 'Active',   phone: '+351 912 000 001', joined: '2023-07-01' },
  { id: 2, name: 'Sofia Andrade',  email: 's.andrade@club.com', role: 'Team Doctor',   status: 'Active',   phone: '+351 912 000 002', joined: '2023-07-01' },
  { id: 3, name: 'Marco Silva',    email: 'm.silva@club.com',   role: 'Fitness Coach', status: 'Active',   phone: '+351 912 000 003', joined: '2024-01-15' },
  { id: 4, name: 'Carlos Mendes',  email: 'c.mendes@club.com',  role: 'Scout',         status: 'Active',   phone: '+351 912 000 004', joined: '2024-06-01' },
  { id: 5, name: 'Ana Ferreira',   email: 'a.ferreira@club.com',role: 'Analyst',       status: 'Active',   phone: '+351 912 000 005', joined: '2024-02-10' },
  { id: 6, name: 'Rui Costa',      email: 'r.costa@club.com',   role: 'Asst. Coach',   status: 'Inactive', phone: '+351 912 000 006', joined: '2022-08-01' },
  { id: 7, name: 'Pedro Nunes',    email: 'p.nunes@club.com',   role: 'Physio',        status: 'Pending',  phone: '+351 912 000 007', joined: '2026-03-01' },
]

// ─── Drills ───────────────────────────────────────────────────────────────────
export const MOCK_DRILLS: Drill[] = [
  {
    id: 1,
    title: 'Rondo 4v2',
    description: 'Four attackers keep possession against two defenders in a 10x10 area. Attackers score a point for every 10 consecutive passes. Rotate defenders after each turnover or on a timer.',
    category: 'Technical',
    level: 'Intermediate',
    durationMins: 15,
    playersMin: 6,
    playersMax: 8,
    objectives: ['Passing', 'Pressing'],
    equipment: ['Cones', 'Bibs', 'Balls'],
    space: '20x20 box',
    coachingPoints: [
      'Support angles — always offer two passing options',
      'Quick one-touch play when pressed',
      'Defenders press together, don\'t split',
      'Body orientation open to receive on the half-turn',
    ],
    tags: ['possession', 'rondo', 'warm-up'],
  },
  {
    id: 2,
    title: 'Pressing Trigger — High Press Unit',
    description: 'Full team shape exercise. Coach plays into a designated zone to trigger the press. Front three and midfield close down as a unit within 3 seconds of the trigger. Back four hold a compressed line.',
    category: 'Tactical',
    level: 'Advanced',
    durationMins: 25,
    playersMin: 14,
    playersMax: 22,
    objectives: ['Pressing', 'Transition'],
    equipment: ['Cones', 'Bibs', 'Balls'],
    space: 'Half pitch',
    coachingPoints: [
      'Identify the trigger (back-pass or side-back receiving)',
      'Front three must press simultaneously, not in sequence',
      'Cut passing lines — force play backwards or into touchline',
      'Midfield compact — no more than 10 m between lines',
      'Recover shape immediately if press is broken',
    ],
    tags: ['pressing', '4-3-3', 'defensive shape'],
  },
  {
    id: 3,
    title: 'Crossing & Finishing Circuit',
    description: 'Wide players deliver crosses from coned positions (byline and cut-back areas). Two strikers and a late-arriving midfielder attack the box. Alternate left and right side every 3 repetitions.',
    category: 'Technical',
    level: 'Intermediate',
    durationMins: 20,
    playersMin: 8,
    playersMax: 14,
    objectives: ['Shooting', 'Positioning'],
    equipment: ['Cones', 'Balls', 'Full-size goals'],
    space: 'Half pitch',
    coachingPoints: [
      'Crosser should assess delivery before touching the ball',
      'Near-post run always first priority for lead striker',
      'Late runner attacks far post or penalty spot',
      'Strike with the correct foot — don\'t wait for a setup touch',
    ],
    tags: ['finishing', 'crossing', 'attacking'],
    youtubeId: 'dQw4w9WgXcQ',
  },
  {
    id: 4,
    title: 'HIIT Sprint Ladder',
    description: 'Players sprint between a series of cones set at 5, 10, 15, 20 and 30 m. Work: 6 seconds max effort. Rest: 20 seconds passive. Complete 8 rounds per set, 3 sets with 3-minute set rest.',
    category: 'Physical',
    level: 'Advanced',
    durationMins: 30,
    playersMin: 4,
    playersMax: 22,
    objectives: ['Recovery'],
    equipment: ['Cones'],
    space: 'Half pitch',
    coachingPoints: [
      'Drive phase — lean forward, powerful arm drive in first 3 steps',
      'Decelerate under control at the cone — don\'t overshoot',
      'Monitor heart rate — target 85–95% max in work periods',
      'Rest is passive, stay standing to maintain circulation',
    ],
    tags: ['speed', 'conditioning', 'HIIT'],
  },
  {
    id: 5,
    title: 'Corner Kick Routine — Flick-On',
    description: 'Designated players positions for a near-post flick-on routine. Delivery targets the first post at head height. Lead runner flicks on, second runner attacks the far post, third player attacks the edge of the box.',
    category: 'Technical',
    level: 'Advanced',
    durationMins: 20,
    playersMin: 10,
    playersMax: 18,
    objectives: ['Positioning', 'Shooting'],
    equipment: ['Cones', 'Balls', 'Full-size goals'],
    space: 'Half pitch',
    coachingPoints: [
      'Corner taker checks positions before running up',
      'Near-post runner times run to arrive a fraction after delivery',
      'Flick-on must be angled downward into goal area',
      'Far-post runner stays wide until the flick-on is made',
      'Blockers hold position to screen opposing defenders',
    ],
    tags: ['set pieces', 'corners', 'attacking'],
  },
  {
    id: 6,
    title: 'Dynamic Warm-Up — Activation Circuit',
    description: 'Progressive 10-minute activation sequence. Includes high knees, butt kicks, lateral shuffles, hip circles, dynamic hamstring sweeps, and 3x short explosive accelerations to finish.',
    category: 'Warm-up',
    level: 'Beginner',
    durationMins: 10,
    playersMin: 4,
    playersMax: 22,
    objectives: ['Recovery'],
    equipment: ['Cones'],
    space: '20x20 box',
    coachingPoints: [
      'Gradual intensity build — easy movements first',
      'Focus on full range of motion, not speed',
      'Final accelerations at 80% effort — not a sprint test',
    ],
    tags: ['warm-up', 'mobility', 'activation'],
  },
  {
    id: 7,
    title: 'Goalkeeper Distribution — Build From Back',
    description: 'GK receives a back-pass and must choose between short distribution to a centre-back, switch to the far fullback, or launch to a pressing target. Coach calls pressure situations to force decision-making.',
    category: 'Goalkeeping',
    level: 'Intermediate',
    durationMins: 15,
    playersMin: 5,
    playersMax: 8,
    objectives: ['Passing', 'Positioning'],
    equipment: ['Cones', 'Balls'],
    space: 'Half pitch',
    coachingPoints: [
      'Scan before receiving — know options before the pass arrives',
      'Short option if press is on, switch if space is available',
      'Distribution with opposite foot when possible to save time',
      'Communication — call the outfield player\'s name before distributing',
    ],
    tags: ['goalkeeping', 'distribution', 'build-up'],
  },
  {
    id: 8,
    title: '3v3 Transition Game',
    description: 'Two teams of 3 in a 30x20 area with small goals at each end. When possession is won, the team in transition has 4 seconds to shoot. No goalkeeper — reward quick counter-attack behaviour.',
    category: 'Tactical',
    level: 'Beginner',
    durationMins: 15,
    playersMin: 6,
    playersMax: 8,
    objectives: ['Transition', 'Shooting'],
    equipment: ['Cones', 'Bibs', 'Small goals', 'Balls'],
    space: '30x20 box',
    coachingPoints: [
      'Win the ball — immediately look forward, not sideways',
      'Third player makes run in behind before the ball is won',
      'Losing team transitions to a compact defensive shape immediately',
      'Reward courage — shots should be encouraged even if speculative',
    ],
    tags: ['transition', 'small-sided', 'attacking'],
  },
]
